services:
  homav-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://api.myhoma.ir}
      - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-300000}
      - VITE_API_IMAGE_PROCESSING_TIMEOUT=${VITE_API_IMAGE_PROCESSING_TIMEOUT:-600000}
      - VITE_UMAMI_SRC=${VITE_UMAMI_SRC:-https://analytics.myhoma.ir/script.js}
      - VITE_UMAMI_WEBSITE_ID=${VITE_UMAMI_WEBSITE_ID:-bbf04a62-584f-4b2e-97b3-6a177ddf093b}
      - VITE_AUTH_MODE=${VITE_AUTH_MODE:-otp}
      - VITE_ENABLE_REALTIME=${VITE_ENABLE_REALTIME:-true}
    networks:
      - homav-network
    labels:
      - "dokploy.app.name=homav-frontend"
      - "dokploy.app.description=HomaV React Frontend Application"
      - "dokploy.app.version=0.1.0"

networks:
  homav-network:
    driver: bridge
    name: homav-network
