type RuntimeConfig = Partial<{
  VITE_API_BASE_URL: string;
  VITE_PUBLIC_MEDIA_BASE_URL: string;
  VITE_PUBLIC_MEDIA_BUCKET: string;
  VITE_API_TIMEOUT: string;
  VITE_API_IMAGE_PROCESSING_TIMEOUT: string;
  VITE_UMAMI_SRC: string;
  VITE_UMAMI_WEBSITE_ID: string;
  VITE_AUTH_MODE: string;
  VITE_ENABLE_UMAMI_IN_DEV: string;
}>;

declare global {
  interface Window {
    __APP_CONFIG__?: RuntimeConfig;
  }
}

const runtimeConfig: RuntimeConfig =
  typeof window !== 'undefined' && window.__APP_CONFIG__
    ? window.__APP_CONFIG__
    : {};

function getString(key: keyof RuntimeConfig, fallback = ''): string {
  const runtimeValue = runtimeConfig[key];
  if (runtimeValue !== undefined && runtimeValue !== '') {
    return runtimeValue;
  }

  const buildTimeValue = import.meta.env[key];
  return buildTimeValue !== undefined && buildTimeValue !== ''
    ? String(buildTimeValue)
    : fallback;
}

function getNumber(key: keyof RuntimeConfig, fallback: number): number {
  const value = Number(getString(key));
  return Number.isFinite(value) && value > 0 ? value : fallback;
}

/**
 * Public frontend configuration.
 *
 * VITE_* values are build-time only in Vite. Production Docker containers load
 * runtime values from /config.js, generated by docker-entrypoint.sh from the
 * container environment supplied by Dokploy Compose.
 */
export const appConfig = {
  apiBaseUrl: getString('VITE_API_BASE_URL', 'http://localhost:8000'),
  // Caching CDN host serving public product/shop images directly from MinIO.
  // Backend now returns fully-formed image URLs, so these are only a fallback
  // for any code path that still builds URLs from a bare object path.
  publicMediaBaseUrl: getString('VITE_PUBLIC_MEDIA_BASE_URL', 'http://localhost:9000'),
  publicMediaBucket: getString('VITE_PUBLIC_MEDIA_BUCKET', 'product-visualizer'),
  apiTimeout: getNumber('VITE_API_TIMEOUT', 30000),
  apiImageProcessingTimeout: getNumber('VITE_API_IMAGE_PROCESSING_TIMEOUT', 180000),
  umamiSrc: getString('VITE_UMAMI_SRC', ''),
  umamiWebsiteId: getString('VITE_UMAMI_WEBSITE_ID', ''),
  authMode: getString('VITE_AUTH_MODE', 'password'),
  enableUmamiInDev: getString('VITE_ENABLE_UMAMI_IN_DEV') === 'true',
};
